// Samarqand & Buxoro CrafTour - Shared Mock Data

export const MOCK_LOCATIONS = [
  // --- SAMARQAND REGION (1-11) ---
  { id: 1, region: 'samarqand', name_en: 'Registan Square', name_ru: 'Площадь Регистан', name_uz: 'Registon maydoni', description_en: 'The heart of ancient Samarkand, featuring three magnificent madrasahs.', description_ru: 'Сердце древнего Самарканда, украшенное тремя величественными медресе.', description_uz: 'Uchta muhtasham madrasadan iborat qadimiy Samarqandning yuragi.', latitude: 39.6548, longitude: 66.9757, category: 'historical', is_out_of_city: false, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1618218168350-6e7c8137558d?auto=format&fit=crop&w=600&q=80' },
  { id: 2, region: 'samarqand', name_en: 'Gur-e-Amir Mausoleum', name_ru: 'Мавзолей Гур-Эмир', name_uz: 'Go\'ri Amir maqbarasi', description_en: 'The final resting place of Amir Temur (Tamerlane).', description_ru: 'Усыпальница Амира Темура (Тамерлана), шедевр архитектуры.', description_uz: 'Amir Temur (Tamerlan) ning so\'nggi qo\'nim topgan joyi, me\'moriy durdona.', latitude: 39.6483, longitude: 66.9692, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=600&q=80' },
  { id: 3, region: 'samarqand', name_en: 'Shah-i-Zinda', name_ru: 'Шахи Зинда', name_uz: 'Shohi Zinda', description_en: 'A breathtaking avenue of blue-domed mausoleums.', description_ru: 'Улица лазурных мавзолеев XI–XV веков.', description_uz: 'Moviy gumbazli maqbaralardan iborat hayratlanarli xiyobon.', latitude: 39.6625, longitude: 66.9878, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1623940179976-b9952ecbc412?auto=format&fit=crop&w=600&q=80' },
  { id: 4, region: 'samarqand', name_en: 'Bibi-Khanym Mosque', name_ru: 'Мечеть Биби-Ханым', name_uz: 'Bibi Xonim masjidi', description_en: 'One of the largest mosques of the 15th century.', description_ru: 'Одна из крупнейших мечетей XV века, построенная в честь любимой жены.', description_uz: 'Amir Temurning sevimli rafiqasi sharafiga qurilgan XV asrning eng yirik masjidlaridan biri.', latitude: 39.6593, longitude: 66.9791, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1605371924599-2c03d64d0dd3?auto=format&fit=crop&w=600&q=80' },
  { id: 5, region: 'samarqand', name_en: 'Ulugh Beg Observatory', name_ru: 'Обсерватория Улугбека', name_uz: 'Ulug\'bek rasadxonasi', description_en: 'Built in 1420, this observatory was a marvel of the Islamic world.', description_ru: 'Историческая обсерватория, бывшая одной из лучших в исламском мире.', description_uz: '1420-yilda qurilgan ushbu rasadxona islom dunyosining ajoyib mo\'jizalaridan biri bo\'lgan.', latitude: 39.6744, longitude: 67.0062, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80' },
  { id: 6, region: 'samarqand', name_en: 'Urgut Mountain Bazaar & Hills', name_ru: 'Ургутский горный базар и горы', name_uz: 'Urgut tog\' bozori va adirlari', description_en: 'Explore traditional crafts at the market and hike through scenic Urgut mountain ranges.', description_ru: 'Посетите традиционный базар и прогуляйтесь по живописным горам Ургута.', description_uz: 'Bozorda an\'anaviy hunarmandchilik bilan tanishing va Urgutning go\'zal tog\' tizmalari bo\'ylab sayr qiling.', latitude: 39.4045, longitude: 67.2435, category: 'alternative', is_out_of_city: true, estimated_duration: 240, image_url: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=600&q=80' },
  { id: 7, region: 'samarqand', name_en: 'Omonqo\'ton Pass & Pines', name_ru: 'Перевал Омонкотон', name_uz: 'Omonqo\'ton dovoni va qarag\'aylari', description_en: 'A majestic pine forest and mountain pass with ancient caves.', description_ru: 'Величественный сосновый лес и горный перевал с древними пещерами.', description_uz: 'Qadimiy g\'orlar va toza buloqlarga ega muhtasham qarag\'ayzor hamda tog\' dovoni.', latitude: 39.3082, longitude: 66.9038, category: 'alternative', is_out_of_city: true, estimated_duration: 180, image_url: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=600&q=80' },
  { id: 8, region: 'samarqand', name_en: 'Konigil Paper Mill', name_ru: 'Бумажная фабрика Конигиль', name_uz: 'Konigil qog\'oz fabrikasi', description_en: 'A peaceful eco-village showcasing the ancient art of Samarkand mulberry paper.', description_ru: 'Эко-деревня, демонстрирующая искусство изготовления шелковой бумаги.', description_uz: 'Samarqand tut qog\'ozini tayyorlashning qadimiy san\'atini namoyish etuvchi tinch eko-qishloq.', latitude: 39.6800, longitude: 67.0180, category: 'alternative', is_out_of_city: true, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80' },
  { id: 9, region: 'samarqand', name_en: 'National Osh House', name_ru: 'Национальный центр плова', name_uz: 'Milliy palov markazi', description_en: 'Authentic Samarkand Osh prepared in giant cauldrons.', description_ru: 'Настоящий самаркандский плов, приготовленный в огромных казанах.', description_uz: 'Katta qozonlarda an\'anaviy retseptlar bo\'yicha tayyorlangan haqiqiy Samarqand palovi.', latitude: 39.6500, longitude: 66.9800, category: 'food', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80' },
  { id: 10, region: 'samarqand', name_en: 'Samarkand Bread Bakery', name_ru: 'Пекарня самаркандских лепешек', name_uz: 'Samarqand nonvoyxonasi', description_en: 'Watch bakers prepare the famous, shiny Samarkand bread in tandyr ovens.', description_ru: 'Наблюдайте за приготовлением знаменитых самаркандских лепешек в тандырах.', description_uz: 'Nonvoylar tandirda mashhur, yaltiroq Samarqand nonlarini yopishini kuzating.', latitude: 39.6600, longitude: 66.9780, category: 'food', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80' },
  { id: 11, region: 'samarqand', name_en: 'Karimbek Restaurant', name_ru: 'Ресторан Каримбек', name_uz: 'Karimbek restorani', description_en: 'Elegant dining featuring traditional shashlik, manti, and music.', description_ru: 'Ресторан с традиционными шашлыками, мантами и музыкой.', description_uz: 'An\'anaviy kabob, manti va jonli milliy musiqa taklif etuvchi ajoyib restoran.', latitude: 39.6521, longitude: 66.9587, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80' },

  // --- BUXORO REGION (12-22) ---
  { id: 12, region: 'buxoro', name_en: 'Po-i-Kalyan Complex', name_ru: 'Комплекс Пои-Калян', name_uz: 'Poyi Kalon majmuasi', description_en: 'A magnificent Islamic religious complex featuring the Kalyan Minaret.', description_ru: 'Величественный религиозный комплекс в центре старой Бухары с минаретом Калян.', description_uz: 'Eski Buxoroning markazida joylashgan muhtasham diniy majmua, Minorai Kalon bilan ajralib turadi.', latitude: 39.7769, longitude: 64.4149, category: 'historical', is_out_of_city: false, estimated_duration: 100, image_url: 'https://images.unsplash.com/photo-1584646098025-97cfbe6cae0d?auto=format&fit=crop&w=600&q=80' },
  { id: 13, region: 'buxoro', name_en: 'Ark of Bukhara', name_ru: 'Цитадель Арк', name_uz: 'Buxoro Arki', description_en: 'A massive 5th-century fortress that was a city within a city for the Emirs.', description_ru: 'Массивная крепость V века, которая когда-то служила резиденцией эмиров.', description_uz: 'Buxoro amirlari yashagan, V asrga oid ulkan qal\'a va shahar ichidagi shahar.', latitude: 39.7779, longitude: 64.4111, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80' },
  { id: 14, region: 'buxoro', name_en: 'Lyabi-Khauz Complex', name_ru: 'Ансамбль Ляби-Хауз', name_uz: 'Labi Hovuz ansambli', description_en: 'A peaceful public square built around a historic pond under old mulberry trees.', description_ru: 'Мирная общественная площадь вокруг исторического пруда, окруженная тутовыми деревьями.', description_uz: 'Ko\'hna chinorlar va asriy tut daraxtlari bilan o\'ralgan, hovuz bo\'yidagi tinch tarixiy maydon.', latitude: 39.7731, longitude: 64.4203, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=600&q=80' },
  { id: 15, region: 'buxoro', name_en: 'Chor Minor', name_ru: 'Чор-Минор', name_uz: 'Chor Minor', description_en: 'A unique historic gatehouse with four decorated turquoise towers.', description_ru: 'Уникальные исторические ворота с четырьмя бирюзовыми башнями.', description_uz: 'To\'rtta moviy gumbazli minoraga ega bo\'lgan betakror va go\'zal tarixiy darvozaxona.', latitude: 39.7749, longitude: 64.4277, category: 'historical', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80' },
  { id: 16, region: 'buxoro', name_en: 'Samanid Mausoleum', name_ru: 'Мавзолей Саманидов', name_uz: 'Somoniylar maqbarasi', description_en: 'A 10th-century masterpiece of early Islamic architecture built of baked bricks.', description_ru: 'Шедевр ранней исламской архитектуры X века, построенный из фигурного кирпича.', description_uz: 'Pishgan g\'isht naqshlaridan bunyod etilgan, X asrga oid ilk islom me\'morchiligining tengsiz durdonasi.', latitude: 39.7772, longitude: 64.4022, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80' },
  { id: 17, region: 'buxoro', name_en: 'Sitorai Mokhi-Khosa Palace', name_ru: 'Дворец Ситораи Мохи-Хоса', name_uz: 'Sitorai Mohi Xosa saroyi', description_en: 'The summer residence of the last Emirs, combining Russian and oriental styles.', description_ru: 'Летняя резиденция последних эмиров Бухары, сочетающая русский и восточный стили.', description_uz: 'Rossiya imperatorlik me\'morchiligi va an\'anaviy sharqona uslubni birlashtirgan so\'nggi Buxoro amirlarining yozgi saroyi.', latitude: 39.8124, longitude: 64.4372, category: 'alternative', is_out_of_city: true, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1608958416790-27ff290c3ce2?auto=format&fit=crop&w=600&q=80' },
  { id: 18, region: 'buxoro', name_en: 'Chor-Bakr Necropolis', name_ru: 'Некрополь Чор-Бакр', name_uz: 'Chor Bakr xotira majmuasi', description_en: 'The "City of the Dead", a massive memorial complex outside Bukhara.', description_ru: '«Город мертвых» — огромный мемориальный комплекс за пределами Бухары.', description_uz: 'Buxorodan tashqarida joylashgan, o\'ziga xos sirli muhitga ega ulkan tarixiy memorial majmua ("O\'liklar shahri").', latitude: 39.7745, longitude: 64.3392, category: 'alternative', is_out_of_city: true, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80' },
  { id: 19, region: 'buxoro', name_en: 'Bukhara Desert Oasis & Dunes', name_ru: 'Пустынный оазис Бухары', name_uz: 'Buxoro sahro vohasi va qum barxanlari', description_en: 'Experience the Kyzylkum Desert with a safari, yurt camps, and camel riding.', description_ru: 'Исследуйте пустыню Кызылкум: сафари, юрты и катание на верблюдах.', description_uz: 'Qizilqum sahrosida tuya minish, milliy o\'tovlarda dam olish va qum barxanlari bo\'ylab ajoyib sayohat.', latitude: 39.9000, longitude: 64.3000, category: 'alternative', is_out_of_city: true, estimated_duration: 240, image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80' },
  { id: 20, region: 'buxoro', name_en: 'Bukhara Spice Market', name_ru: 'Рынок специй Бухары', name_uz: 'Buxoro ziravorlar bozori', description_en: 'A sensory journey offering exotic spices and herbal teas under ancient trading domes.', description_ru: 'Древние торговые купола со специями, сухофруктами и травяными чаями.', description_uz: 'Qadimgi savdo gumbazlari ostida joylashgan, xushbo\'y ziravorlar, quruq mevalar va shifobaxsh choylar bozori.', latitude: 39.7745, longitude: 64.4172, category: 'food', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80' },
  { id: 21, region: 'buxoro', name_en: 'Labi Hovuz Tea House', name_ru: 'Чайхана Ляби-Хауз', name_uz: 'Labi Hovuz choyxonasi', description_en: 'Dine by the water, enjoying Bukhara pilaf and green tea under ancient trees.', description_ru: 'Обед у воды исторического пруда, наслаждаясь бухарским пловом.', description_uz: 'Labi Hovuz bo\'yidagi asriy chinorlar soyasida milliy buxorocha palov va ko\'k choydan bahramand bo\'ling.', latitude: 39.7733, longitude: 64.4206, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80' },
  { id: 22, region: 'buxoro', name_en: 'Minzifa Restaurant', name_ru: 'Ресторан Минзифа', name_uz: 'Minzifa restorani', description_en: 'A fine dining restaurant with a rooftop terrace overlooking the historic domes.', description_ru: 'Ресторан изысканной кухни с террасой на крыше и видом на Бухару.', description_uz: 'Buxoroning ko\'hna gumbazlariga qaragan tom qismidagi ayvonga ega bo\'lgan milliy va yevropa taomlari restorani.', latitude: 39.7740, longitude: 64.4185, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80' }
];

export const MOCK_GUIDES = [
  // Samarqand Guides
  { id: 1, region: 'samarqand', full_name: 'Sherzod Alimov', phone_number: '+998901234567' },
  { id: 2, region: 'samarqand', full_name: 'Elena Petrova', phone_number: '+998937654321' },
  { id: 3, region: 'samarqand', full_name: 'Jahongir Rustamov', phone_number: '+998971112233' },
  // Buxoro Guides
  { id: 4, region: 'buxoro', full_name: 'Mukhammadkhon Bakhronov', phone_number: '+998939991122' },
  { id: 5, region: 'buxoro', full_name: 'Malika Davlatova', phone_number: '+998904445566' },
  { id: 6, region: 'buxoro', full_name: 'Abdurakhmon Karimov', phone_number: '+998998887766' }
];

export const MOCK_TARIFFS = [
  // Samarqand Guides language tariffs
  { id: 1, guide_id: 1, language_code: 'EN', daily_rate: 50.00 },
  { id: 2, guide_id: 1, language_code: 'RU', daily_rate: 40.00 },
  { id: 3, guide_id: 1, language_code: 'UZ', daily_rate: 35.00 },
  { id: 4, guide_id: 2, language_code: 'RU', daily_rate: 45.00 },
  { id: 5, guide_id: 2, language_code: 'FR', daily_rate: 65.00 },
  { id: 6, guide_id: 3, language_code: 'EN', daily_rate: 60.00 },
  { id: 7, guide_id: 3, language_code: 'RU', daily_rate: 50.00 },
  { id: 8, guide_id: 3, language_code: 'ES', daily_rate: 70.00 },
  { id: 9, guide_id: 3, language_code: 'UZ', daily_rate: 45.00 },
  
  // Buxoro Guides language tariffs (starting with guide_id 4)
  { id: 10, guide_id: 4, language_code: 'EN', daily_rate: 45.00 },
  { id: 11, guide_id: 4, language_code: 'RU', daily_rate: 40.00 },
  { id: 12, guide_id: 4, language_code: 'UZ', daily_rate: 30.00 },
  { id: 13, guide_id: 5, language_code: 'EN', daily_rate: 50.00 },
  { id: 14, guide_id: 5, language_code: 'FR', daily_rate: 60.00 },
  { id: 15, guide_id: 6, language_code: 'DE', daily_rate: 55.00 },
  { id: 16, guide_id: 6, language_code: 'RU', daily_rate: 45.00 },
  { id: 17, guide_id: 6, language_code: 'UZ', daily_rate: 35.00 }
];

export const MOCK_VEHICLES = [
  // Samarqand Vehicles
  { id: 1, region: 'samarqand', driver_name: 'Alisher aka', driver_phone: '+998909998877', car_model: 'Chevrolet Cobalt (White)', car_number: '01 A 777 BA', city_rate: 30.00, out_of_city_rate: 45.00, capacity: 5 },
  { id: 2, region: 'samarqand', driver_name: 'Doston aka', driver_phone: '+998935554433', car_model: 'Chevrolet Gentra (Black)', car_number: '01 Z 888 ZZ', city_rate: 35.00, out_of_city_rate: 50.00, capacity: 5 },
  { id: 3, region: 'samarqand', driver_name: 'Sarvar aka', driver_phone: '+998993332211', car_model: 'Chevrolet Gentra (Silver)', car_number: '01 Y 555 YY', city_rate: 35.00, out_of_city_rate: 50.00, capacity: 5 },
  { id: 4, region: 'samarqand', driver_name: 'Odil aka', driver_phone: '+998901234567', car_model: 'Hyundai H1 Minivan (Silver)', car_number: '01 X 777 XX', city_rate: 50.00, out_of_city_rate: 75.00, capacity: 8 },
  { id: 5, region: 'samarqand', driver_name: 'Jahongir aka', driver_phone: '+998909876543', car_model: 'Isuzu Bus (Turquoise)', car_number: '01 B 999 BB', city_rate: 120.00, out_of_city_rate: 180.00, capacity: 20 },
  
  // Buxoro Vehicles
  { id: 6, region: 'buxoro', driver_name: 'Jafar aka', driver_phone: '+998903334455', car_model: 'Chevrolet Lacetti (White)', car_number: '80 A 123 BZ', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 7, region: 'buxoro', driver_name: 'Rustam aka', driver_phone: '+998936667788', car_model: 'Chevrolet Cobalt (Grey)', car_number: '80 B 555 YY', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 8, region: 'buxoro', driver_name: 'Bekzod aka', driver_phone: '+998972223344', car_model: 'Toyota Hiace Minivan (White)', car_number: '80 C 777 XX', city_rate: 55.00, out_of_city_rate: 80.00, capacity: 10 }
];

export const UZ_LOCATIONS = {
  1: { name: 'Registon maydoni', desc: 'Uchta muhtasham madrasadan iborat qadimiy Samarqandning yuragi.' },
  2: { name: 'Go\'ri Amir maqbarasi', desc: 'Amir Temur (Tamerlan) ning so\'nggi qo\'nim topgan joyi, me\'moriy durdona.' },
  3: { name: 'Shohi Zinda', desc: 'Moviy gumbazli maqbaralardan iborat hayratlanarli xiyobon.' },
  4: { name: 'Bibi Xonim masjidi', desc: 'Amir Temurning sevimli rafiqasi sharafiga qurilgan XV asrning eng yirik masjidlaridan biri.' },
  5: { name: 'Ulug\'bek rasadxonasi', desc: '1420-yilda qurilgan ushbu rasadxona islom dunyosining ajoyib mo\'jizalaridan biri bo\'lgan.' },
  6: { name: 'Urgut tog\' bozori va adirlari', desc: 'Bozorda an\'anaviy hunarmandchilik bilan tanishing va Urgutning go\'zal tog\' tizmalari bo\'ylab sayr qiling.' },
  7: { name: 'Omonqo\'ton dovoni va qarag\'aylari', desc: 'Qadimiy g\'orlar va toza buloqlarga ega muhtasham qarag\'ayzor hamda tog\' dovoni.' },
  8: { name: 'Konigil qog\'oz fabrikasi', desc: 'Samarqand tut qog\'ozini tayyorlashning qadimiy san\'atini namoyish etuvchi tinch eko-qishloq.' },
  9: { name: 'Milliy palov markazi', desc: 'Katta qozonlarda an\'anaviy retseptlar bo\'yicha tayyorlangan haqiqiy Samarqand palovi.' },
  10: { name: 'Samarqand nonvoyxonasi', desc: 'Nonvoylar tandirda mashhur, yaltiroq Samarqand nonlarini yopishini kuzating.' },
  11: { name: 'Karimbek restorani', desc: 'An\'anaviy kabob, manti va jonli milliy musiqa taklif etuvchi ajoyib restoran.' },
  
  12: { name: 'Poyi Kalon majmuasi', desc: 'Minorai Kalon bilan bezatilgan, Buxoroning ko\'hna va muhtasham diniy ansambli.' },
  13: { name: 'Buxoro Arki', desc: 'Buxoro amirlarining qadimiy qarorgohi, shahar ichidagi tarixiy qal\'a.' },
  14: { name: 'Labi Hovuz ansambli', desc: 'Ko\'hna chinorlar va hovuz atrofida joylashgan, Buxoroning eng mashhur madaniy maydoni.' },
  15: { name: 'Chor Minor', desc: 'To\'rtta moviy gumbazli minoraga ega bo\'lgan o\'ziga xos tarixiy obida.' },
  16: { name: 'Somoniylar maqbarasi', desc: 'Pishgan g\'ishtdan yuksak mahorat bilan qurilgan, X asr me\'morchilik shohasari.' },
  17: { name: 'Sitorai Mohi Xosa saroyi', desc: 'Sharq va Yevropa uslublari uyg\'unlashgan Buxoro amirlarining yozgi saroyi.' },
  18: { name: 'Chor Bakr xotira majmuasi', desc: 'Buxorodan tashqaridagi ulkan maqbaralar va bog\'lardan iborat memorial majmua.' },
  19: { name: 'Buxoro sahro vohasi va qum barxanlari', desc: 'Qizilqum cho\'lida tuya minish va sahro tabiatidan bahramand bo\'lish sayohati.' },
  20: { name: 'Buxoro ziravorlar bozori', desc: 'Tarixiy gumbazlar ostidagi sharqona xushbo\'y ziravorlar va quruq mevalar bozori.' },
  21: { name: 'Labi Hovuz choyxonasi', desc: 'Tarixiy hovuz bo\'yida buxorocha milliy taomlar va shirin choy taklif etuvchi joy.' },
  22: { name: 'Minzifa restorani', desc: 'Buxoro eski shahar gumbazlarining ajoyib manzarasini ko\'rsatuvchi premium restoran.' }
};
