// Samarqand & Buxoro CrafTour - Shared Mock Data

export const MOCK_LOCATIONS = [
  // --- SAMARQAND REGION (1-11) ---
  { id: 1, region: 'samarqand', name_en: 'Registan Square', name_ru: 'Площадь Регистан', name_uz: 'Registon maydoni', description_en: 'The heart of ancient Samarkand, featuring three magnificent madrasahs.', description_ru: 'Сердце древнего Самарканда, украшенное тремя величественными медресе.', description_uz: 'Uchta muhtasham madrasadan iborat qadimiy Samarqandning yuragi.', latitude: 39.6548, longitude: 66.9757, category: 'historical', is_out_of_city: false, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1618218168350-6e7c8137558d?auto=format&fit=crop&w=600&q=80' },
  { id: 2, region: 'samarqand', name_en: 'Gur-e-Amir Mausoleum', name_ru: 'Мавзолей Гур-Эмир', name_uz: 'Go\'ri Amir maqbarasi', description_en: 'The final resting place of Amir Temur (Tamerlane).', description_ru: 'Усыпальница Амира Темура (Тамерлана), шедевр архитектуры.', description_uz: 'Amir Temur (Tamerlan) ning so\'nggi qo\'nim topgan joyi, me\'moriy durdona.', latitude: 39.6483, longitude: 66.9692, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=600&q=80' },
  { id: 3, region: 'samarqand', name_en: 'Shah-i-Zinda', name_ru: 'Шахи Зинда', name_uz: 'Shohi Zinda', description_en: 'A breathtaking avenue of blue-domed mausoleums.', description_ru: 'Улица лазурных мавзолеев XI–XV веков.', description_uz: 'Moviy gumbazli maqbaralardan iborat hayratlanarli xiyobon.', latitude: 39.6625, longitude: 66.9878, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1623940179976-b9952ecbc412?auto=format&fit=crop&w=600&q=80' },
  { id: 4, region: 'samarqand', name_en: 'Bibi-Khanym Mosque', name_ru: 'Мечеть Биби-Ханым', name_uz: 'Bibi Xonim masjidi', description_en: 'One of the largest mosques of the 15th century.', description_ru: 'Одна из крупнейших мечетей XV века, построенная в честь любимой жены.', description_uz: 'Amir Temurning sevimli rafiqasi sharafiga qurilgan XV asrning eng yirik masjidlaridan biri.', latitude: 39.6593, longitude: 66.9791, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1605371924599-2c03d64d0dd3?auto=format&fit=crop&w=600&q=80' },
  { id: 5, region: 'samarqand', name_en: 'Ulugh Beg Observatory', name_ru: 'Обсерватория Улугбека', name_uz: 'Ulug\'bek rasadxonasi', description_en: 'Built in 1420, this observatory was a marvel of the Islamic world.', description_ru: 'Историческая обсерватория, бывшая одной из лучших в исламском мире.', description_uz: '1420-yilda qurilgan ushbu rasadxona islom dunyosining ajoyib mo\'jizalaridan biri bo\'lgan.', latitude: 39.6744, longitude: 67.0062, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80' },
  { id: 6, region: 'samarqand', name_en: 'Urgut Mountain Bazaar & Hills', name_ru: 'Ургутский горный базар и горы', name_uz: 'Urgut tog\' bozori va adirlari', description_en: 'Explore traditional crafts at the market and hike through scenic Urgut mountain ranges.', description_ru: 'Посетите традиционный базар и прогуляйтесь по живописным горам Ургута.', description_uz: 'Bozorda an\'anaviy hunarmandchilik bilan tanishing va Urgutning go\'zal tog\' tizmalari bo\'ylab sayr qiling.', latitude: 39.4045, longitude: 67.2435, category: 'alternative', is_out_of_city: true, estimated_duration: 240, image_url: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=600&q=80' },
  { id: 7, region: 'samarqand', name_en: 'Omonqo\'ton Pass & Pines', name_ru: 'Перевал Омонкотон', name_uz: 'Omonqo\'ton dovoni va qarag\'aylari', description_en: 'A majestic pine forest and mountain pass with ancient caves.', description_ru: 'Величественный сосновый лес и горный перевал с древними пещерами.', description_uz: 'Qadimiy g\'orlar va toza buloqlarga ega muhtasham qarag\'ayzor hamda tog\' dovoni.', latitude: 39.3082, longitude: 66.9038, category: 'alternative', is_out_of_city: true, estimated_duration: 180, image_url: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=600&q=80' },
  { id: 8, region: 'samarqand', name_en: 'Konigil Paper Mill', name_ru: 'Бумажная фабрика Конигиль', name_uz: 'Konigil qog\'oz fabrikasi', description_en: 'A peaceful eco-village showcasing the ancient art of Samarkand mulberry paper.', description_ru: 'Эко-деревня, демонстрирующая искусство изготовления шелковой бумаги.', description_uz: 'Samarqand tut qog\'ozini tayyorlashning qadimiy san\'atini namoyish etuvchi tinch eko-qishloq.', latitude: 39.6800, longitude: 67.0180, category: 'alternative', is_out_of_city: true, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80' },
  { id: 9, region: 'samarqand', name_en: 'National Osh House', name_ru: 'Национальный центр плова', name_uz: 'Milliy palov markazi', description_en: 'Authentic Samarkand Osh prepared in giant cauldrons.', description_ru: 'Настоящий самаркандский плов, приготовленный в огромных казанах.', description_uz: 'Katta qozonlarda an\'anaviy retseptlar bo\'yicha tayyorlangan haqiqiy Samarqand palovi.', latitude: 39.6500, longitude: 66.9800, category: 'food', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80' },
  { id: 10, region: 'samarqand', name_en: 'Samarkand Bread Bakery', name_ru: 'Пекарня самаркандских лепешек', name_uz: 'Samarqand nonvoyxonasi', description_en: 'Watch bakers prepare the famous, shiny Samarkand bread in tandyr ovens.', description_ru: 'Наблюдайте за приготовлением знаменитых самаркандских лепешек в тандырах.', description_uz: 'Nonvoylar tandirda mashhur, yaltiroq Samarqand nonlarini yopishini kuzating.', latitude: 39.6600, longitude: 66.9780, category: 'food', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80' },
  { id: 11, region: 'samarqand', name_en: 'Karimbek Restaurant', name_ru: 'Ресторан Каримбек', name_uz: 'Karimbek restorani', description_en: 'Elegant dining featuring traditional shashlik, manti, and music.', description_ru: 'Ресторан с традиционными шашлыками, мантами и музыкой.', description_uz: 'An\'anaviy kabob, manti va jonli milliy musiqa taklif etuvchi ajoyib restoran.', latitude: 39.6521, longitude: 66.9587, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80' },

  // --- BUXORO REGION (12-22) ---
  { id: 12, region: 'buxoro', name_en: 'Po-i-Kalyan Complex', name_ru: 'Комплекс Пои-Калян', name_uz: 'Poyi Kalon majmuasi', description_en: 'A magnificent Islamic religious complex featuring the Kalyan Minaret.', description_ru: 'Величественный религиозный комплекс в центре старой Бухары с минаретом Калян.', description_uz: 'Eski Buxoroning markazida joylashgan muhtasham diniy majmua, Minorai Kalon bilan ajralib turadi.', latitude: 39.7769, longitude: 64.4149, category: 'historical', is_out_of_city: false, estimated_duration: 100, image_url: 'https://images.unsplash.com/photo-1584646098025-97cfbe6cae0d?auto=format&fit=crop&w=600&q=80' },
  { id: 13, region: 'buxoro', name_en: 'Ark of Bukhara', name_ru: 'Цитадель Арк', name_uz: 'Buxoro Arki', description_en: 'A massive 5th-century fortress that was a city within a city for the Emirs.', description_ru: 'Массивная крепость V века, которая когда-то служила резиденцией эмиров.', description_uz: 'Buxoro amirlari yashagan, V asrga oid ulkan qal\'a va shahar ichidagi shahar.', latitude: 39.7779, longitude: 64.4111, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80' },
  { id: 14, region: 'buxoro', name_en: 'Lyabi-Khauz Complex', name_ru: 'Ансамбль Ляби-Хауз', name_uz: 'Labi Hovuz ansambli', description_en: 'A peaceful public square built around a historic pond under old mulberry trees.', description_ru: 'Мирная общественная площадь вокруг исторического пруда, окруженная тутовыми деревьями.', description_uz: 'Ko\'hna chinorlar va asriy tut daraxtlari bilan o\'ralgan, hovuz bo\'yidagi tinch tarixiy maydon.', latitude: 39.7731, longitude: 64.4203, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=600&q=80' },
  { id: 15, region: 'buxoro', name_en: 'Chor Minor', name_ru: 'Чор-Минор', name_uz: 'Chor Minor', description_en: 'A unique historic gatehouse with four decorated turquoise towers.', description_ru: 'Уникальные исторические ворота с четырьмя бирюзовыми башнями.', description_uz: 'To\'rtta moviy gumbazli minoraga ega bo\'lgan betakror va go\'zal tarixiy darvozaxona.', latitude: 39.7749, longitude: 64.4277, category: 'historical', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80' },
  { id: 16, region: 'buxoro', name_en: 'Samanid Mausoleum', name_ru: 'Мавзолей Саманидов', name_uz: 'Somoniylar maqbarasi', description_en: 'A 10th-century masterpiece of early Islamic architecture built of baked bricks.', description_ru: 'Шедевр ранней исламской архитектуры X века, построенный из фигурного кирпича.', description_uz: 'Pishgan g\'isht naqshlaridan bunyod etilgan, X asrga oid ilk islom me\'morchiligining tengsiz durdonasi.', latitude: 39.7772, longitude: 64.4022, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80' },
  { id: 17, region: 'buxoro', name_en: 'Sitorai Mokhi-Khosa Palace', name_ru: 'Дворец Ситораи Мохи-Хоса', name_uz: 'Sitorai Mohi Xosa saroyi', description_en: 'The summer residence of the last Emirs, combining Russian and oriental styles.', description_ru: 'Летняя резиденция последних эмиров Бухары, сочетающая русский и восточный стили.', description_uz: 'Rossiya imperatorlik me\'morchiligi va an\'anaviy sharqona uslubni birlashtirgan so\'nggi Buxoro amirlarinin yozgi saroyi.', latitude: 39.8124, longitude: 64.4372, category: 'alternative', is_out_of_city: true, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1608958416790-27ff290c3ce2?auto=format&fit=crop&w=600&q=80' },
  { id: 18, region: 'buxoro', name_en: 'Chor-Bakr Necropolis', name_ru: 'Некрополь Чор-Бакр', name_uz: 'Chor Bakr xotira majmuasi', description_en: 'The "City of the Dead", a massive memorial complex outside Bukhara.', description_ru: '«Город мертвых» — огромный мемориальный комплекс за пределами Бухары.', description_uz: 'Buxorodan tashqarida joylashgan, o\'ziga xos sirli muhitga ega ulkan tarixiy memorial majmua ("O\'liklar shahri").', latitude: 39.7745, longitude: 64.3392, category: 'alternative', is_out_of_city: true, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80' },
  { id: 19, region: 'buxoro', name_en: 'Bukhara Desert Oasis & Dunes', name_ru: 'Пустынный оазис Бухары', name_uz: 'Buxoro sahro vohasi va qum barxanlari', description_en: 'Experience the Kyzylkum Desert with a safari, yurt camps, and camel riding.', description_ru: 'Исследуйте пустыню Кызылкум: сафари, юрты и катание на верблюдах.', description_uz: 'Qizilqum sahrosida tuya minish, milliy o\'tovlarda dam olish va qum barxanlari bo\'ylab ajoyib sayohat.', latitude: 39.9000, longitude: 64.3000, category: 'alternative', is_out_of_city: true, estimated_duration: 240, image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80' },
  { id: 20, region: 'buxoro', name_en: 'Bukhara Spice Market', name_ru: 'Рынок специй Бухары', name_uz: 'Buxoro ziravorlar bozori', description_en: 'A sensory journey offering exotic spices and herbal teas under ancient trading domes.', description_ru: 'Древние торговые купола со специями, сухофруктами и травяными чаями.', description_uz: 'Qadimgi savdo gumbazlari ostida joylashgan, xushbo\'y ziravorlar, quruq mevalar va shifobaxsh choylar bozori.', latitude: 39.7745, longitude: 64.4172, category: 'food', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80' },
  { id: 21, region: 'buxoro', name_en: 'Labi Hovuz Tea House', name_ru: 'Чайхана Ляби-Хауз', name_uz: 'Labi Hovuz choyxonasi', description_en: 'Dine by the water, enjoying Bukhara pilaf and green tea under ancient trees.', description_ru: 'Обед у воды исторического пруда, наслаждаясь бухарским пловом.', description_uz: 'Labi Hovuz bo\'yidagi asriy chinorlar soyasida milliy buxorocha palov va ko\'k choydan bahramand bo\'ling.', latitude: 39.7733, longitude: 64.4206, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80' },
  { id: 22, region: 'buxoro', name_en: 'Minzifa Restaurant', name_ru: 'Ресторан Минзифа', name_uz: 'Minzifa restorani', description_en: 'A fine dining restaurant with a rooftop terrace overlooking the historic domes.', description_ru: 'Ресторан изысканной кухни с террасой на крыше и видом на Бухару.', description_uz: 'Buxoroning ko\'hna gumbazlariga qaragan tom qismidagi ayvonga ega bo\'lgan milliy va yevropa taomlari restorani.', latitude: 39.7740, longitude: 64.4185, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80' },

  // --- XORAZM REGION (23-33) ---
  { id: 23, region: 'xorazm', name_en: 'Ichan-Kala Complex', name_ru: 'Ичан-Кала', name_uz: 'Ichan Qal\'a majmuasi', description_en: 'The ancient walled inner city of Khiva, containing over 50 historic monuments.', description_ru: 'Древний внутренний город Хивы, обнесенный стеной, включающий более 50 памятников архитектуры.', description_uz: 'Xivaning qadimiy devor bilan o\'ralgan ichki shahri, 50 dan ortiq tarixiy obidalarni o\'z ichiga oladi.', latitude: 41.3783, longitude: 60.3639, category: 'historical', is_out_of_city: false, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1584646098025-97cfbe6cae0d?auto=format&fit=crop&w=600&q=80' },
  { id: 24, region: 'xorazm', name_en: 'Kalta-Minor Minaret', name_ru: 'Минарет Кальта-Минор', name_uz: 'Kalta Minor minorasi', description_en: 'An iconic, unfinished minaret covered in vibrant turquoise glazed tiles.', description_ru: 'Культовый недостроенный минарет, полностью покрытый глазурованной бирюзовой плиткой.', description_uz: 'Yorqin firuza va ko\'k rangli sirlangan koshinlar bilan qoplangan Xivaning ramzi bo\'lgan chala qolgan minora.', latitude: 41.3781, longitude: 60.3635, category: 'historical', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80' },
  { id: 25, region: 'xorazm', name_en: 'Tash-Khauli Palace', name_ru: 'Дворец Таш-Хаули', name_uz: 'Toshhovli saroyi', description_en: 'A grand palace of the Khans of Khiva featuring ornate blue wall tiles.', description_ru: 'Дворец хивинских ханов с великолепной синей майоликой и изысканной резьбой.', description_uz: 'Moviy koshinlar va nafis yog\'och o\'ymakorligi bilan bezatilgan Xiva xonlarining hashamatli saroyi.', latitude: 41.3788, longitude: 60.3644, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=600&q=80' },
  { id: 26, region: 'xorazm', name_en: 'Kunya-Ark Citadel', name_ru: 'Крепость Куня-Арк', name_uz: 'Ko\'hna Ark qal\'asi', description_en: 'The fortified palace-city of the Khiva Khans, featuring a high watchtower.', description_ru: 'Укрепленная цитадель и бывшая резиденция ханов с прекрасной смотровой башней.', description_uz: 'Xiva xonlarining qal\'a-saroyi bo\'lib, uning tarkibida zarbxona, masjidlar va ko\'rinish minorasi mavjud.', latitude: 41.3782, longitude: 60.3598, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80' },
  { id: 27, region: 'xorazm', name_en: 'Juma Mosque', name_ru: 'Джума-мечеть', name_uz: 'Juma masjidi', description_en: 'A unique mosque supported by 218 beautifully carved wooden columns.', description_ru: 'Уникальная мечеть X века, поддерживаемая 218 резными деревянными колоннами.', description_uz: '218 ta nafis o\'yilgan yog\'och ustunlar bilan jihozlangan X asrga oid o\'ziga xos masjid.', latitude: 41.3784, longitude: 60.3626, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80' },
  { id: 28, region: 'xorazm', name_en: 'Islam Khodja Complex', name_ru: 'Минарет и медресе Ислам-Ходжа', name_uz: 'Islomxo\'ja majmuasi', description_en: 'The tallest minaret in Khiva, offering panoramic views of Ichan-Kala.', description_ru: 'Самый высокий минарет в Хиве с прекрасным панорамным видом на Ичан-Калу.', description_uz: 'Ichan Qal\'aning ajoyib manzarasini ko\'rsatuvchi Xivadagi eng baland minora va uning madrasasi.', latitude: 41.3773, longitude: 60.3629, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1608958416790-27ff290c3ce2?auto=format&fit=crop&w=600&q=80' },
  { id: 29, region: 'xorazm', name_en: 'Pahlavan Mahmoud Mausoleum', name_ru: 'Мавзолей Пахлавана Махмуда', name_uz: 'Pahlavon Mahmud maqbarasi', description_en: 'The sacred final resting place of Khiva\'s patron saint, with a massive turquoise dome.', description_ru: 'Священная усыпальница покровителя Хивы с величественным бирюзовым куполом.', description_uz: 'Xivaning muqaddas homiysi dafn etilgan, ulkan firuza gumbazga ega muhtasham ziyoratgoh.', latitude: 41.3768, longitude: 60.3618, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80' },
  { id: 30, region: 'xorazm', name_en: 'Tozabog Summer Palace', name_ru: 'Дворец Кибла Тозабог', name_uz: 'Qibla Tozabog\' saroyi', description_en: 'The summer palace of the last Khivan Khans, set inside a green oasis.', description_ru: 'Загородный летний дворец последних хивинских ханов в зеленом оазисе.', description_uz: 'Shahar devorlaridan tashqarida joylashgan Xiva xonlarining yozgi saroyi va yashil bog\'i.', latitude: 41.3524, longitude: 60.3472, category: 'alternative', is_out_of_city: true, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80' },
  { id: 31, region: 'xorazm', name_en: 'Khiva Silk Workshop', name_ru: 'Шелковая мастерская Хивы', name_uz: 'Xiva ipak hunarmandchilik ustaxonasi', description_en: 'Watch local weavers create natural silk carpets and traditional suzanis.', description_ru: 'Мастерская шелковых ковров и традиционных сюзане, создаваемых вручную.', description_uz: 'Qadimgi dastgohlarda tabiiy ipak gilamlar va milliy suzanilarni to\'qish jarayonini kuzating.', latitude: 41.3780, longitude: 60.3620, category: 'alternative', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80' },
  { id: 32, region: 'xorazm', name_en: 'Khorezm Osh & Shivit Oshi', name_ru: 'Ресторан Шивит Оши', name_uz: 'Xorazm shivit oshi markazi', description_en: 'Dine on traditional green dill noodles topped with meat stew, a Khiva specialty.', description_ru: 'Отведайте традиционную зеленую лапшу с укропом (Шивит Оши) и хорезмский плов.', description_uz: 'Xivaning o\'ziga xos milliy taomi bo\'lgan shivitli ko\'k lagmon (shivit oshi) va xorazmcha palov restorani.', latitude: 41.3779, longitude: 60.3615, category: 'food', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80' },
  { id: 33, region: 'xorazm', name_en: 'Tukhum Barak Eatery', name_ru: 'Кафе Тухум Барак', name_uz: 'Tuxum barak choyxonasi', description_en: 'A traditional tavern serving Khorezmian egg-filled dumplings, hand-made to order.', description_ru: 'Кафе традиционной кухни, специализирующееся на хорезмских варениках с яйцом.', description_uz: 'Xorazm oshxonasining mashhur tuxum barak taomini yangi va issiq tayyorlab beruvchi milliy choyxona.', latitude: 41.3789, longitude: 60.3625, category: 'food', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80' },
  // --- SHAHRISABZ REGION (34-39) ---
  { id: 34, region: 'shahrisabz', name_en: 'Ak-Saray Palace ruins', name_ru: 'Руины дворца Ак-Сарай', name_uz: 'Oqsaroy saroyi xarobalari', description_en: 'The colossal summer palace built by Amir Temur, featuring remains of majestic blue and gold tilework.', description_ru: 'Колоссальные руины летней резиденции Амира Темура с остатками величественной мозаики.', description_uz: 'Amir Temur tomonidan barpo etilgan muhtasham va ulkan Oqsaroy saroyining moviy koshinli xarobalari.', latitude: 39.0606, longitude: 66.8294, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1584646098025-97cfbe6cae0d?auto=format&fit=crop&w=600&q=80' },
  { id: 35, region: 'shahrisabz', name_en: 'Kok Gumbaz Mosque (Dorut Tilavat)', name_ru: 'Мечеть Кок-Гумбаз', name_uz: 'Ko\'k Gumbaz masjidi (Dorut Tilovat)', description_en: 'The main Friday mosque of Shahrisabz, built by Ulugh Beg, famous for its giant emerald-blue tiled dome.', description_ru: 'Главная пятничная мечеть города, построенная Улугбеком, с гигантским бирюзовым куполом.', description_uz: 'Ulug\'bek tomonidan qurilgan, ulkan firuza-moviy gumbazga ega bo\'lgan Xondamir jome masjidi.', latitude: 39.0506, longitude: 66.8281, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80' },
  { id: 36, region: 'shahrisabz', name_en: 'Dorus Saodat Complex', name_ru: 'Комплекс Дорус-Саодат', name_uz: 'Dorus Saodat majmuasi', description_en: 'The family mausoleum of the Temurids, containing Jahongir\'s tomb and grand vaulted structures.', description_ru: 'Семейная усыпальница Темуридов с мавзолеем Джахангира и грандиозными сводами.', description_uz: 'Temuriylar sulolasining oilaviy maqbarasi bo\'lib, u yerda Jahongir mirzo qabri va ravotlar joylashgan.', latitude: 39.0515, longitude: 66.8315, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=600&q=80' },
  { id: 37, region: 'shahrisabz', name_en: 'Crypt of Amir Temur', name_ru: 'Склеп Амира Темура', name_uz: 'Amir Temur xilxonasi', description_en: 'A underground stone chamber with a massive marble sarcophagus designed originally for Tamerlane.', description_ru: 'Подземная каменная усыпальница с саркофагом, изначально созданным для самого Темура.', description_uz: 'Temur bobomiz uchun maxsus tayyorlangan, yer ostidagi ulkan marmar toshli tobut va xilxona.', latitude: 39.0518, longitude: 66.8322, category: 'historical', is_out_of_city: false, estimated_duration: 45, image_url: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80' },
  { id: 38, region: 'shahrisabz', name_en: 'Shahrisabz Chorsu Bazaar', name_ru: 'Чорсу Базар Шахрисабза', name_uz: 'Shahrisabz Chorsu bozori', description_en: 'A domed 18th-century bazaar located at the ancient crossroads, offering local textiles and dry fruits.', description_ru: 'Купольный старинный базар XVIII века на историческом перекрестке с тканями и сухофруктами.', description_uz: 'Qadimiy chorrahada joylashgan, milliy matolar va quruq mevalar sotiladigan gumbazli XVIII asr bozori.', latitude: 39.0531, longitude: 66.8298, category: 'alternative', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80' },
  { id: 39, region: 'shahrisabz', name_en: 'Katta-Langar Mountain Tandoor', name_ru: 'Горный тандыр Катта-Лангара', name_uz: 'Katta Langar tog\' tandir kabobi', description_en: 'An open-air restaurant in the scenic mountains serving traditional meat cooked in clay ovens.', description_ru: 'Ресторан в живописных горах, где подают традиционное мясо из глиняных печей с хвоей арчи.', description_uz: 'Tog\' bag\'rida archa barglari bilan tuproq tandirda pishirilgan haqiqiy tog\' tandir kabob choyxonasi.', latitude: 38.8320, longitude: 66.7562, category: 'food', is_out_of_city: true, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80' },

  // --- TOSHKENT REGION (40-45) ---
  { id: 40, region: 'toshkent', name_en: 'Amir Temur Square', name_ru: 'Площадь Амира Темура', name_uz: 'Amir Temur maydoni', description_en: 'The grand central square of Tashkent, featuring an equestrian statue of Amir Temur surrounded by lush parks and fountains.', description_ru: 'Главная центральная площадь Ташкента с конной статуей Амира Темура, окружённой парками и фонтанами.', description_uz: 'Toshkentning markaziy maydonida Amir Temurning otliq haykali, yashil parklar va favvoralar bilan bezatilgan.', latitude: 41.2995, longitude: 69.2401, category: 'historical', is_out_of_city: false, estimated_duration: 60, image_url: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=600&q=80' },
  { id: 41, region: 'toshkent', name_en: 'Khast Imam Complex', name_ru: 'Комплекс Хаст-Имам', name_uz: 'Hazrat Imom majmuasi', description_en: 'The spiritual heart of Tashkent, home to one of the world\'s oldest Quran manuscripts and stunning Islamic architecture.', description_ru: 'Духовный центр Ташкента с одной из старейших рукописей Корана и великолепной исламской архитектурой.', description_uz: 'Toshkentning ma\'naviy markazi — dunyodagi eng qadimiy Qur\'on qo\'lyozmasi va ajoyib islom me\'morchiligi.', latitude: 41.3053, longitude: 69.2313, category: 'historical', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1618218168350-6e7c8137558d?auto=format&fit=crop&w=600&q=80' },
  { id: 42, region: 'toshkent', name_en: 'Chorsu Bazaar', name_ru: 'Рынок Чорсу', name_uz: 'Chorsu bozori', description_en: 'Tashkent\'s iconic ancient bazaar under a massive turquoise dome, overflowing with spices, produce, and local crafts.', description_ru: 'Легендарный базар Ташкента под огромным бирюзовым куполом: специи, овощи и народные промыслы.', description_uz: 'Ulkan firuza gumbaz ostidagi Toshkentning mashhur Chorsu bozori — ziravorlar, mahsulotlar va hunarmandchilik.', latitude: 41.3094, longitude: 69.2284, category: 'alternative', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80' },
  { id: 43, region: 'toshkent', name_en: 'Navoi Opera & Ballet Theatre', name_ru: 'Театр оперы и балета им. Навои', name_uz: 'Navoiy nomidagi Opera va Balet teatri', description_en: 'A magnificent Stalinist-era opera house blending Soviet grandeur with Uzbek architectural motifs, a cultural landmark.', description_ru: 'Величественный оперный театр эпохи сталинизма, сочетающий советское величие с узбекскими мотивами.', description_uz: 'Sovet davri me\'morchiligi va o\'zbek naqshlari uyg\'unlashgan muhtasham opera va balet teatri.', latitude: 41.2975, longitude: 69.2413, category: 'historical', is_out_of_city: false, estimated_duration: 120, image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deceeaf7?auto=format&fit=crop&w=600&q=80' },
  { id: 44, region: 'toshkent', name_en: 'Tashkent TV Tower & Park', name_ru: 'Ташкентская телебашня и парк', name_uz: 'Toshkent teleminorasi va park', description_en: 'Central Asia\'s tallest structure at 375m, offering panoramic views of Tashkent from its observation deck and restaurant.', description_ru: 'Самое высокое сооружение Центральной Азии высотой 375 м с панорамным видом на Ташкент.', description_uz: 'Markaziy Osiyoning eng baland inshootiga (375m) chiqib Toshkentning ajoyib panoramasini tomosha qiling.', latitude: 41.3160, longitude: 69.2781, category: 'alternative', is_out_of_city: false, estimated_duration: 90, image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80' },
  { id: 45, region: 'toshkent', name_en: 'Norin & Dimlama Restaurant', name_ru: 'Ресторан Норин и Димлама', name_uz: 'Norin va Dimlama restorani', description_en: 'Taste authentic Tashkent cuisine — hand-pulled norin noodles and slow-cooked dimlama stew in a traditional setting.', description_ru: 'Попробуйте аутентичную ташкентскую кухню: норин, думляма и другие традиционные блюда.', description_uz: 'Qo\'lda tortilgan norin va sekin pishirilgan dimlama taomini an\'anaviy muhitda tatib ko\'ring.', latitude: 41.2988, longitude: 69.2395, category: 'food', is_out_of_city: false, estimated_duration: 75, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80' }
];

export const MOCK_GUIDES = [
  // Samarqand Guides
  { id: 1, region: 'samarqand', full_name: 'Sherzod Alimov', phone_number: '+998901234567' },
  { id: 2, region: 'samarqand', full_name: 'Elena Petrova', phone_number: '+998937654321' },
  { id: 3, region: 'samarqand', full_name: 'Jahongir Rustamov', phone_number: '+998971112233' },
  // Buxoro Guides
  { id: 4, region: 'buxoro', full_name: 'Mukhammadkhon Bakhronov', phone_number: '+998939991122' },
  { id: 5, region: 'buxoro', full_name: 'Malika Davlatova', phone_number: '+998904445566' },
  { id: 6, region: 'buxoro', full_name: 'Abdurakhmon Karimov', phone_number: '+998998887766' },
  // Xorazm Guides
  { id: 7, region: 'xorazm', full_name: 'Khurshid Bekchanov', phone_number: '+998935552233' },
  { id: 8, region: 'xorazm', full_name: 'Zilola Masharipova', phone_number: '+998904441122' },
  { id: 9, region: 'xorazm', full_name: 'Davron Sabirov', phone_number: '+998973336655' },
  // Shahrisabz Guides
  { id: 10, region: 'shahrisabz', full_name: 'Javokhir Qodirov', phone_number: '+998933334455' },
  { id: 11, region: 'shahrisabz', full_name: 'Madina Karimova', phone_number: '+998905556677' },
  // Toshkent Guides
  { id: 12, region: 'toshkent', full_name: 'Nodira Yusupova', phone_number: '+998901234599' },
  { id: 13, region: 'toshkent', full_name: 'Sardor Toshmatov', phone_number: '+998935559988' }
];

export const MOCK_TARIFFS = [
  // Samarqand Guides language tariffs
  { id: 1, guide_id: 1, language_code: 'EN', daily_rate: 50.00 },
  { id: 2, guide_id: 1, language_code: 'RU', daily_rate: 40.00 },
  { id: 3, guide_id: 1, language_code: 'UZ', daily_rate: 35.00 },
  { id: 4, guide_id: 2, language_code: 'RU', daily_rate: 45.00 },
  { id: 5, guide_id: 2, language_code: 'FR', daily_rate: 65.00 },
  { id: 6, guide_id: 3, language_code: 'EN', daily_rate: 60.00 },
  { id: 7, guide_id: 3, language_code: 'RU', daily_rate: 50.00 },
  { id: 8, guide_id: 3, language_code: 'ES', daily_rate: 70.00 },
  { id: 9, guide_id: 3, language_code: 'UZ', daily_rate: 45.00 },
  
  // Buxoro Guides language tariffs (starting with guide_id 4)
  { id: 10, guide_id: 4, language_code: 'EN', daily_rate: 45.00 },
  { id: 11, guide_id: 4, language_code: 'RU', daily_rate: 40.00 },
  { id: 12, guide_id: 4, language_code: 'UZ', daily_rate: 30.00 },
  { id: 13, guide_id: 5, language_code: 'EN', daily_rate: 50.00 },
  { id: 14, guide_id: 5, language_code: 'FR', daily_rate: 60.00 },
  { id: 15, guide_id: 6, language_code: 'DE', daily_rate: 55.00 },
  { id: 16, guide_id: 6, language_code: 'RU', daily_rate: 45.00 },
  { id: 17, guide_id: 6, language_code: 'UZ', daily_rate: 35.00 },
  
  // Xorazm Guides language tariffs
  { id: 18, guide_id: 7, language_code: 'EN', daily_rate: 50.00 },
  { id: 19, guide_id: 7, language_code: 'RU', daily_rate: 40.00 },
  { id: 20, guide_id: 7, language_code: 'UZ', daily_rate: 35.00 },
  { id: 21, guide_id: 8, language_code: 'DE', daily_rate: 55.00 },
  { id: 22, guide_id: 8, language_code: 'RU', daily_rate: 45.00 },
  { id: 23, guide_id: 8, language_code: 'UZ', daily_rate: 35.00 },
  { id: 24, guide_id: 9, language_code: 'EN', daily_rate: 55.00 },
  { id: 25, guide_id: 9, language_code: 'RU', daily_rate: 45.00 },
  { id: 26, guide_id: 9, language_code: 'ES', daily_rate: 65.00 },
  // Shahrisabz Guide tariffs
  { id: 27, guide_id: 10, language_code: 'EN', daily_rate: 50.00 },
  { id: 28, guide_id: 10, language_code: 'RU', daily_rate: 40.00 },
  { id: 29, guide_id: 10, language_code: 'UZ', daily_rate: 35.00 },
  { id: 30, guide_id: 11, language_code: 'EN', daily_rate: 55.00 },
  { id: 31, guide_id: 11, language_code: 'RU', daily_rate: 45.00 },
  { id: 32, guide_id: 11, language_code: 'FR', daily_rate: 65.00 },
  // Toshkent Guide tariffs
  { id: 33, guide_id: 12, language_code: 'EN', daily_rate: 60.00 },
  { id: 34, guide_id: 12, language_code: 'RU', daily_rate: 50.00 },
  { id: 35, guide_id: 12, language_code: 'UZ', daily_rate: 40.00 },
  { id: 36, guide_id: 13, language_code: 'EN', daily_rate: 65.00 },
  { id: 37, guide_id: 13, language_code: 'RU', daily_rate: 55.00 },
  { id: 38, guide_id: 13, language_code: 'KO', daily_rate: 80.00 }
];

export const MOCK_VEHICLES = [
  // Samarqand Vehicles
  { id: 1, region: 'samarqand', driver_name: 'Alisher aka', driver_phone: '+998909998877', car_model: 'Chevrolet Cobalt (White)', car_number: '01 A 777 BA', city_rate: 30.00, out_of_city_rate: 45.00, capacity: 5 },
  { id: 2, region: 'samarqand', driver_name: 'Doston aka', driver_phone: '+998935554433', car_model: 'Chevrolet Gentra (Black)', car_number: '01 Z 888 ZZ', city_rate: 35.00, out_of_city_rate: 50.00, capacity: 5 },
  { id: 3, region: 'samarqand', driver_name: 'Sarvar aka', driver_phone: '+998993332211', car_model: 'Chevrolet Gentra (Silver)', car_number: '01 Y 555 YY', city_rate: 35.00, out_of_city_rate: 50.00, capacity: 5 },
  { id: 4, region: 'samarqand', driver_name: 'Odil aka', driver_phone: '+998901234567', car_model: 'Hyundai H1 Minivan (Silver)', car_number: '01 X 777 XX', city_rate: 50.00, out_of_city_rate: 75.00, capacity: 8 },
  { id: 5, region: 'samarqand', driver_name: 'Jahongir aka', driver_phone: '+998909876543', car_model: 'Isuzu Bus (Turquoise)', car_number: '01 B 999 BB', city_rate: 120.00, out_of_city_rate: 180.00, capacity: 20 },
  
  // Buxoro Vehicles
  { id: 6, region: 'buxoro', driver_name: 'Jafar aka', driver_phone: '+998903334455', car_model: 'Chevrolet Lacetti (White)', car_number: '80 A 123 BZ', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 7, region: 'buxoro', driver_name: 'Rustam aka', driver_phone: '+998936667788', car_model: 'Chevrolet Cobalt (Grey)', car_number: '80 B 555 YY', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 8, region: 'buxoro', driver_name: 'Bekzod aka', driver_phone: '+998972223344', car_model: 'Toyota Hiace Minivan (White)', car_number: '80 C 777 XX', city_rate: 55.00, out_of_city_rate: 80.00, capacity: 10 },
  
  // Xorazm Vehicles
  { id: 9, region: 'xorazm', driver_name: 'Dilshod aka', driver_phone: '+998931112233', car_model: 'Chevrolet Cobalt (Grey)', car_number: '90 B 123 XY', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 10, region: 'xorazm', driver_name: 'Sanjar aka', driver_phone: '+998904447788', car_model: 'Chevrolet Lacetti (White)', car_number: '90 A 999 AA', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 11, region: 'xorazm', driver_name: 'Mansur aka', driver_phone: '+998977778899', car_model: 'Toyota Hiace Minivan (White)', car_number: '90 C 777 ZZ', city_rate: 55.00, out_of_city_rate: 80.00, capacity: 10 },
  
  // Shahrisabz Vehicles
  { id: 12, region: 'shahrisabz', driver_name: 'Sherzod aka', driver_phone: '+998901113344', car_model: 'Chevrolet Cobalt (Grey)', car_number: '90 D 555 AA', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  { id: 13, region: 'shahrisabz', driver_name: 'Bobur aka', driver_phone: '+998934448899', car_model: 'Chevrolet Lacetti (White)', car_number: '90 E 888 ZZ', city_rate: 25.00, out_of_city_rate: 40.00, capacity: 5 },
  // Toshkent Vehicles
  { id: 14, region: 'toshkent', driver_name: 'Aziz aka', driver_phone: '+998901998877', car_model: 'Chevrolet Equinox (Black)', car_number: '01 T 001 TT', city_rate: 45.00, out_of_city_rate: 65.00, capacity: 5 },
  { id: 15, region: 'toshkent', driver_name: 'Mirzo aka', driver_phone: '+998935001122', car_model: 'Toyota Camry (White)', car_number: '01 T 002 TK', city_rate: 55.00, out_of_city_rate: 80.00, capacity: 5 }
];

export const UZ_LOCATIONS = {
  1: { name: 'Registon maydoni', desc: 'Uchta muhtasham madrasadan iborat qadimiy Samarqandning yuragi.' },
  2: { name: 'Go\'ri Amir maqbarasi', desc: 'Amir Temur (Tamerlan) ning so\'nggi qo\'nim topgan joyi, me\'moriy durdona.' },
  3: { name: 'Shohi Zinda', desc: 'Moviy gumbazli maqbaralardan iborat hayratlanarli xiyobon.' },
  4: { name: 'Bibi Xonim masjidi', desc: 'Amir Temurning sevimli rafiqasi sharafiga qurilgan XV asrning eng yirik masjidlaridan biri.' },
  5: { name: 'Ulug\'bek rasadxonasi', desc: '1420-yilda qurilgan ushbu rasadxona islom dunyosining ajoyib mo\'jizalaridan biri bo\'lgan.' },
  6: { name: 'Urgut tog\' bozori va adirlari', desc: 'Bozorda an\'anaviy hunarmandchilik bilan tanishing va Urgutning go\'zal tog\' tizmalari bo\'ylab sayr qiling.' },
  7: { name: 'Omonqo\'ton dovoni va qarag\'aylari', desc: 'Qadimiy g\'orlar va toza buloqlarga ega muhtasham qarag\'ayzor hamda tog\' dovoni.' },
  8: { name: 'Konigil qog\'oz fabrikasi', desc: 'Samarqand tut qog\'ozini tayyorlashning qadimiy san\'atini namoyish etuvchi tinch eko-qishloq.' },
  9: { name: 'Milliy palov markazi', desc: 'Katta qozonlarda an\'anaviy retseptlar bo\'yicha tayyorlangan haqiqiy Samarqand palovi.' },
  10: { name: 'Samarqand nonvoyxonasi', desc: 'Nonvoylar tandirda mashhur, yaltiroq Samarqand nonlarini yopishini kuzating.' },
  11: { name: 'Karimbek restorani', desc: 'An\'anaviy kabob, manti va jonli milliy musiqa taklif etuvchi ajoyib restoran.' },
  
  12: { name: 'Poyi Kalon majmuasi', desc: 'Minorai Kalon bilan bezatilgan, Buxoroning ko\'hna va muhtasham diniy ansambli.' },
  13: { name: 'Buxoro Arki', desc: 'Buxoro amirlarining qadimiy qarorgohi, shahar ichidagi tarixiy qal\'a.' },
  14: { name: 'Labi Hovuz ansambli', desc: 'Ko\'hna chinorlar va hovuz atrofida joylashgan, Buxoroning eng mashhur madaniy maydoni.' },
  15: { name: 'Chor Minor', desc: 'To\'rtta moviy gumbazli minoraga ega bo\'lgan o\'ziga xos tarixiy obida.' },
  16: { name: 'Somoniylar maqbarasi', desc: 'Pishgan g\'ishtdan yuksak mahorat bilan qurilgan, X asr me\'morchilik shohasari.' },
  17: { name: 'Sitorai Mohi Xosa saroyi', desc: 'Sharq va Yevropa uslublari uyg\'unlashgan Buxoro amirlarining yozgi saroyi.' },
  18: { name: 'Chor Bakr xotira majmuasi', desc: 'Buxorodan tashqaridagi ulkan maqbaralar va bog\'lardan iborat memorial majmua.' },
  19: { name: 'Buxoro sahro vohasi va qum barxanlari', desc: 'Qizilqum cho\'lida tuya minish va sahro tabiatidan bahramand bo\'lish sayohati.' },
  20: { name: 'Buxoro ziravorlar bozori', desc: 'Tarixiy gumbazlar ostidagi sharqona xushbo\'y ziravorlar va quruq mevalar bozori.' },
  21: { name: 'Labi Hovuz choyxonasi', desc: 'Tarixiy hovuz bo\'yida buxorocha milliy taomlar va shirin choy taklif etuvchi joy.' },
  22: { name: 'Minzifa restorani', desc: 'Buxoro eski shahar gumbazlarining ajoyib manzarasini ko\'rsatuvchi premium restoran.' },

  // --- SHAHRISABZ REGION ---
  34: { name: 'Oqsaroy saroyi xarobalari', desc: 'Amir Temur tomonidan barpo etilgan muhtasham va ulkan Oqsaroy saroyining moviy koshinli xarobalari.' },
  35: { name: 'Ko\'k Gumbaz masjidi (Dorut Tilavat)', desc: 'Ulug\'bek tomonidan qurilgan, ulkan firuza-moviy gumbazga ega bo\'lgan Xondamir jome masjidi.' },
  36: { name: 'Dorus Saodat majmuasi', desc: 'Temuriylar sulolasining oilaviy maqbarasi bo\'lib, u yerda Jahongir mirzo qabri va ravotlar joylashgan.' },
  37: { name: 'Amir Temur xilxonasi', desc: 'Temur bobomiz uchun maxsus tayyorlangan, yer ostidagi ulkan marmar toshli tobut va xilxona.' },
  38: { name: 'Shahrisabz Chorsu bozori', desc: 'Qadimiy chorrahada joylashgan, milliy matolar va quruq mevalar sotiladigan gumbazli XVIII asr bozori.' },
  39: { name: 'Katta Langar tog\' tandir kabobi', desc: 'Tog\' bag\'rida archa barglari bilan tuproq tandirda pishirilgan haqiqiy tog\' tandir kabob choyxonasi.' },

  // --- TOSHKENT REGION ---
  40: { name: 'Amir Temur maydoni', desc: 'Toshkentning markaziy maydonida Amir Temurning otliq haykali, yashil parklar va favvoralar bilan bezatilgan.' },
  41: { name: 'Hazrat Imom majmuasi', desc: 'Toshkentning ma\'naviy markazi — dunyodagi eng qadimiy Qur\'on qo\'lyozmasi va ajoyib islom me\'morchiligi.' },
  42: { name: 'Chorsu bozori', desc: 'Ulkan firuza gumbaz ostidagi Toshkentning mashhur Chorsu bozori — ziravorlar, mahsulotlar va hunarmandchilik.' },
  43: { name: 'Navoiy nomidagi Opera va Balet teatri', desc: 'Sovet davri me\'morchiligi va o\'zbek naqshlari uyg\'unlashgan muhtasham opera va balet teatri.' },
  44: { name: 'Toshkent teleminorasi va park', desc: 'Markaziy Osiyoning eng baland inshootiga (375m) chiqib Toshkentning ajoyib panoramasini tomosha qiling.' },
  45: { name: 'Norin va Dimlama restorani', desc: 'Qo\'lda tortilgan norin va sekin pishirilgan dimlama taomini an\'anaviy muhitda tatib ko\'ring.' }
};
